# Generated by Django 5.1.1 on 2024-09-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=255)),
                ('purchaser_address', models.CharField(max_length=255)),
                ('purchaser_mobile', models.CharField(max_length=15)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_address', models.CharField(max_length=255)),
                ('property_address', models.CharField(max_length=255)),
                ('title_search', models.CharField(max_length=255)),
                ('settlement_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
