# Generated by Django 5.2.2 on 2025-07-02 12:53

import django.db.models.deletion
import settlements_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("acn", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("postcode", models.CharField(blank=True, default="", max_length=10)),
                ("state", models.CharField(blank=True, default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_reference",
                    models.CharField(
                        default=settlements_app.models.generate_file_reference,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "purchaser_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "purchaser_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "purchaser_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "purchaser_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "seller_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seller_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "title_search",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("lodge_mortgage", "Register Mortgage"),
                            ("discharge_mortgage", "Discharge Mortgage"),
                        ],
                        default="purchase",
                        max_length=100,
                    ),
                ),
                ("settlement_date", models.DateField(blank=True, null=True)),
                ("lodgement_date", models.DateField(blank=True, null=True)),
                ("settlement_time", models.TimeField(blank=True, null=True)),
                ("title_reference", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("ready", "Ready"),
                            ("settling", "Settling"),
                            ("settled", "Settled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_street_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "transaction_street_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_suburb",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_postcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("house", "House"),
                            ("unit", "Unit/Townhouse"),
                            ("vacant_land", "Vacant Land"),
                            ("commercial", "Commercial"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company_abn", models.CharField(blank=True, max_length=50, null=True)),
                ("company_acn", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_1_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_1_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "director_1_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_1_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_2_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_2_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "director_2_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_2_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_3_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_3_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "director_3_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_3_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_4_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_4_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "director_4_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_4_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_5_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_5_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "director_5_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_5_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="chat_files/"),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="settlements/documents/")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("title_search", "Title Search"),
                            ("id_verification", "Verification of ID"),
                            ("form_qro_d2", "Form QRO D2"),
                            ("trust_document", "Trust Document"),
                            ("asic_extract", "ASIC Extract"),
                            ("gst_withholding", "GST Withholding"),
                        ],
                        default="contract",
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instruction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="settlements_app.instruction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pexa_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "instruction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_direction",
                        to="settlements_app.instruction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDirectionLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional_fees", "Professional Fees"),
                            ("lodgement_fees", "Lodgement Fees"),
                            ("pexa_fees", "PEXA Fees"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "account_name",
                    models.CharField(default="Unnamed Account", max_length=100),
                ),
                (
                    "account_details",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("owner", models.CharField(blank=True, default="", max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="settlements_app.paymentdirection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("two_factor_authenticated", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solicitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructing_solicitor", models.CharField(max_length=255)),
                (
                    "office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("solicitor", "Solicitor"),
                            ("conveyancer", "Conveyancer"),
                            ("other", "Other"),
                        ],
                        default="solicitor",
                        max_length=20,
                    ),
                ),
                (
                    "law_society_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "conveyancer_license",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitors",
                        to="settlements_app.firm",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instruction",
            name="solicitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructions",
                to="settlements_app.solicitor",
            ),
        ),
    ]
