# Generated by Django 5.2.2 on 2025-07-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdirectionlineitem",
            name="direction_type",
            field=models.CharField(
                choices=[("purchaser", "Purchaser"), ("vendor", "Vendor")],
                default="purchaser",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentdirectionlineitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("body_corp", "Body Corporate Fees"),
                    ("council_rates", "Council Rates"),
                    ("gst_withholding", "GST Withholding"),
                    ("linked_settlement", "Linked Financial Settlement"),
                    ("other", "Other"),
                    ("bpay", "Other (BPAY)"),
                    ("professional_fees", "Professional Fees"),
                    ("qld_land_tax", "QLD Land Tax"),
                    ("third_party_beneficiary", "Third Party Beneficiary"),
                    ("vendor_funds", "Vendor's Funds"),
                    ("water_rates", "Water Rates"),
                    ("agent_fees", "Real Estate Agent Fees"),
                    ("stamp_duty", "Stamp Duty"),
                    ("lodgement_fee", "Lodgement Fee"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
