# Generated by Django 5.1.1 on 2025-01-01 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements_app', '0002_solicitor_instruction_solicitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='client_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='instruction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='settlement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('mortgage', 'Mortgage')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
