# Generated by Django 5.2.2 on 2025-07-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0002_paymentdirectionlineitem_direction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruction",
            name="adjustments",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="deposit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
