# Generated by Django 5.2.2 on 2025-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settlements_app",
            "0003_instruction_adjustments_instruction_deposit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="deposit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
