# Generated by Django 4.0.6 on 2025-02-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements_app', '0003_instruction_client_name_instruction_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='purchaser_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='purchaser_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='purchaser_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='seller_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='settlement_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='solicitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settlements_app.solicitor'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='title_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitor',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
