# Generated by Django 4.0.6 on 2025-02-03 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements_app', '0004_alter_instruction_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='purchaser_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='solicitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlements_app.solicitor'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='title_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
