# Generated by Django 5.2.2 on 2025-07-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0004_alter_instruction_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdirection",
            name="funds_available_to_settle",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Manually entered amount showing funds available to settle",
                max_digits=12,
                null=True,
            ),
        ),
    ]
