# Generated by Django 5.2.2 on 2025-07-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0005_paymentdirection_funds_available_to_settle"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatesAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("adjusted", "Adjusted as Paid"),
                            ("owing", "Owing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cts_apportionment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "arrears_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_owing", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payee", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
