# Generated by Django 4.0.6 on 2025-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements_app', '0006_instruction_file_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='property_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='purchaser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='settlement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('lodge_mortgage', 'Lodge Mortgage'), ('discharge_mortgage', 'Discharge Mortgage')], default='purchase', max_length=100),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
