# Generated by Django 4.0.6 on 2025-02-06 11:16

from django.db import migrations, models
import settlements_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements_app', '0007_alter_instruction_property_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='file_reference',
            field=models.CharField(default=settlements_app.models.generate_file_reference, max_length=50, unique=True),
        ),
    ]
