# Generated by Django 5.2.2 on 2025-07-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0007_ratesadjustment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratesadjustment",
            name="instruction",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates_adjustments",
                to="settlements_app.instruction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ratesadjustment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
