# Generated by Django 4.0.6 on 2025-02-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements_app', '0008_alter_instruction_file_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='solicitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='settlements_app.solicitor'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='settlements/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='settlements_app.instruction')),
            ],
        ),
    ]
