# Generated by Django 5.1.5 on 2025-02-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0009_alter_instruction_solicitor_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruction",
            name="settlement_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="file_reference",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
