# Generated by Django 5.1.5 on 2025-02-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0010_instruction_settlement_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruction",
            name="title_reference",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
