# Generated by Django 5.1.5 on 2025-02-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0011_instruction_title_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("contract", "Contract"),
                    ("title_search", "Title search"),
                    ("id_verification", "Verification of ID"),
                    ("form_qro_d2", "Form QRO D2"),
                    ("trust_document", "Trust document"),
                    ("asic_extract", "ASIC extract"),
                    ("gst_withholding", "GST withholding"),
                ],
                default="contract",
                max_length=50,
            ),
        ),
    ]
