# Generated by Django 5.1.5 on 2025-02-16 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0012_document_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Firm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="solicitor",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="solicitor",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="solicitor",
            name="firm_name",
        ),
        migrations.AddField(
            model_name="solicitor",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitors",
                to="settlements_app.firm",
            ),
        ),
    ]
