# Generated by Django 5.1.5 on 2025-02-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0013_firm_remove_solicitor_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="acn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="firm",
            name="postcode",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="firm",
            name="state",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="solicitor",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="solicitor",
            name="office_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="solicitor",
            name="role",
            field=models.CharField(
                choices=[
                    ("solicitor", "Solicitor"),
                    ("conveyancer", "Conveyancer"),
                    ("other", "Other"),
                ],
                default="solicitor",
                max_length=20,
            ),
        ),
    ]
