# Generated by Django 5.1.5 on 2025-02-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "settlements_app",
            "0014_firm_acn_firm_address_firm_postcode_firm_state_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="solicitor",
            old_name="role",
            new_name="profession",
        ),
    ]
