# Generated by Django 4.0.6 on 2025-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements_app', '0015_rename_role_solicitor_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ready', 'Ready'), ('settling', 'Settling'), ('settled', 'Settled')], default='pending', max_length=20),
        ),
    ]
