# Generated by Django 5.1.6 on 2025-02-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "settlements_app",
            "0019_chatmessage_recipient_alter_chatmessage_created_at_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
