# Generated by Django 5.1.6 on 2025-02-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0021_chatmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="receiver",
            new_name="recipient",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="read",
        ),
    ]
