# Generated by Django 5.1.6 on 2025-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0022_rename_receiver_chatmessage_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
