# Generated by Django 4.2.19 on 2025-03-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0023_chatmessage_is_read_alter_chatmessage_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitor",
            name="conveyancer_license",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="solicitor",
            name="law_society_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
