# Generated by Django 5.2.2 on 2025-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0026_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instruction",
            name="property_address",
        ),
        migrations.AddField(
            model_name="instruction",
            name="company_abn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="company_acn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="company_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_1_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_1_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_1_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_1_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_2_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_2_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_2_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_2_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_3_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_3_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_3_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_3_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_4_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_4_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_4_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_4_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_5_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_5_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_5_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="director_5_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="lodgement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="transaction_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="settlement_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("lodge_mortgage", "Register Mortgage"),
                    ("discharge_mortgage", "Discharge Mortgage"),
                ],
                default="purchase",
                max_length=100,
            ),
        ),
    ]
