# Generated by Django 5.2.2 on 2025-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements_app", "0027_remove_instruction_property_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instruction",
            name="transaction_address",
        ),
        migrations.AddField(
            model_name="instruction",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("house", "House"),
                    ("unit", "Unit/Townhouse"),
                    ("vacant_land", "Vacant Land"),
                    ("commercial", "Commercial"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="transaction_postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="transaction_state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="transaction_street_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="transaction_street_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="transaction_suburb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
